_target_: src.models.model.Model
network:
    _target_: src.models.unet.UNet
    in_channels: 96 # 12*8+9
    n_classes: 48 # 6*8
    depth: 5
    wf: 6
    padding: True
    up_mode: 'upconv'
    batch_norm: True

dataset:
  _target_: src.data.dataset.T4CDataset
  root_dir: "subset3days"
    #limit: 200
  use_npy: False
  limit:
  sampling_height: 1
  sampling_width: 1
  reduced: False

  # TODO detach transform and have it separate?
  transform:
    _target_: src.data.transform.UNetTransform
    stack_time: True
    pre_batch_dim: False
    post_batch_dim: True
    crop_pad: [6,6,1,0]
    num_channels: 8

valset: True
valset_limit:
