_target_: src.models.model.Model
network:
    _target_: src.models.unet.UNet
    in_channels: 105 # 12*8+9
    out_channels: 6 # 6*8
    depth: 2
    wf: 6
    padding: True
    up_mode: 'upconv'
    batch_norm: True

dataset:
  _target_: src.data.dataset.T4CDataset
  root_dir: "7daysv6"
  limit:
  use_npy: False
  sampling_height: 1
  sampling_width: 1
  dim_start: 0
  dim_step: 1
  output_start: 0
  output_step: 2
  reduced: False
  single_channel: 0
  time_step:
  perm: True

valset: True
valset_limit: 10
val_filter: "**/validation/*8ch.h5"
