
_target_: src.models.model.Model
network:
    _target_: src.models.unet.UNet
    in_channels: 105 # 12*8+9
    n_classes: 6 # 6*8
    depth: 5
    wf: 6
    padding: True
    up_mode: 'upconv'
    batch_norm: True

dataset:
  _target_: src.data.dataset.T4CDataset
  root_dir: "/home/shehel/ml/traffic_forecasting/data/raw/debug"#"7days"
    #limit: 200
  use_npy: False
  limit:
  sampling_height: 1
  sampling_width: 1
  dim_start: 0
  dim_step: 1
  output_start: 0
  output_step: 1
  reduced: False
  single_channel: 2
  time_step:
  perm: False

  # TODO detach transform and have it separate?
  transform:
    _target_: src.data.transform.UNetTransform
    pre_batch_dim: False
    post_batch_dim: True
    crop_pad: [6,6,1,0]
    num_channels: 6

valset: True
valset_limit:
val_filter: "**/validation/*8ch.h5"
