_target_: src.models.model.Model
network:
    _target_: src.models.unet.UNet
    in_channels: 105 # 12*8+9
    out_channels: 48 # 6*8
    depth: 2
    wf: 6
    padding: True
    up_mode: 'upconv'
    batch_norm: True
    pos_emb: False

dataset:
  _target_: src.data.dataset.T4CDataset
  root_dir: "7days"
  limit:
  use_npy: False
  sampling_height: 1
  sampling_width: 1
  dim_start: 0
  dim_step: 1
  output_start: 0
  output_step: 1
  reduced: False
  single_channel:
  time_step: 
  perm: False

valset: True
valset_limit:
val_filter: "**/validation/*8ch.h5"
