_target_: src.models.model.Model
network:
    _target_: src.models.mlp.MLP
    in_channels: 576  # 12*8+9
    out_channels: 4 # 6*8
    hidden_size: 128
    dropout : 0.2

dataset:
  _target_: src.data.dataset.T4CDataset
  root_dir: "7days"
  limit:
  use_npy: False
  sampling_height: 1
  sampling_width: 1
  dim_start: 0
  dim_step: 1
  output_start: 1
  output_step: 2
  reduced: False
  single_channel: 
  time_step: random
  perm: False

valset: True
valset_limit:
val_filter: "**/validation/*8ch.h5"

