_target_: src.models.model.Model
network:
    _target_: src.models.unet_fact.Unet3D
    dim: 8 # 12*8+9
    out_dim: 8 # 6*8

dataset:
  _target_: src.data.dataset_fact.T4CDataset
  root_dir: "7daysv6"
  limit:
  use_npy: False
  sampling_height: 1
  sampling_width: 1
  dim_start: 0
  dim_step: 1
  output_start: 0
  output_step: 1
  reduced: False
  single_channel:
  time_step:
  perm: False

valset: True
valset_limit: 10
val_filter: "**/validation/*8ch.h5"
