_target_: src.models.Model
network:
    _target_: src.models.Unet
    in_channels: 105 # 12*8+9
    n_classes: 48 # 6*8
    depth: 5
    wf: 6
    padding: True
    up_mode: "upconv"
    batch_norm: True

dataset:
  _target_: src.data.dataset.T4CDataset
  data_transform:
    _target_: src.data.transform.UNetTransform
    stack_time: True
    pre_batch_dim: False
    post_batch_dim: True
    crop_pad: [6,6,1,0]
    num_channels: 8
