random_seed: 123

train_fraction: 1
val_fraction: 0
resume_checkpoint:
device: 'cuda'
epochs: 30
data_parallel: false
device_ids:
amp_mode:
scaler:
optimizer:
  lr: 1e-4
  weight_decay: 0.0001
dataloader:
  shuffle: True
  batch_size: 4
  num_workers: 4
  train_eval: 1000
