random_seed: 123

train_fraction: 0.9
val_fraction: 0.1
resume_checkpoint: null
device: 'cuda'
epochs: 1
data_parallel: True
optimizer:
  lr: 1e-4
  weight_decay: 0.0001
dataloader:
  shuffle: True
  batch_size: 8
  num_workers: 8
