random_seed: 123

train_fraction: 1
val_fraction: 0
resume_checkpoint: null
device: 'cuda'
epochs: 3
data_parallel: False
optimizer:
  lr: 1e-4
  weight_decay: 0.0001
dataloader:
  shuffle: True
  batch_size: 8
  num_workers: 4
