random_seed: 123
train_fraction: 1
val_fraction: 0
resume_checkpoint:
epochs: 20
parallel_backend: "nccl"
n_process: 4
amp_mode: amp
scaler: true
optimizer:
  lr: 1e-4
  weight_decay: 0.0001
dataloader:
  shuffle: True
  batch_size: 32
  num_workers: 8
  train_eval: 1000
transform:
  in_h: 128
  in_w: 128
  pad_tuple:
  - 0
  - 0
  - 0
  - 0
  static: False
