random_seed: 123
train_fraction: 1
val_fraction: 0
resume_checkpoint: #ae73c90a9df34ff3a911e13f0d05cff9
epochs: 3
parallel_backend: #"nccl"
n_process:
amp_mode:
scaler:
optimizer:
  lr: 1e-4
  weight_decay: 0.0001
dataloader:
  shuffle: True
  batch_size: 2
  num_workers: 0
  train_eval: 10
transform:
  in_h: 495
  in_w: 436
  pad_tuple:
  - 6
  - 6
  - 1
  - 0
  static: True
