random_seed: 123
train_fraction: 1
val_fraction: 0
resume_checkpoint:
residual: 
epochs: 100
parallel_backend: 
n_process: 
amp_mode:
scaler:
optimizer:
  lr: 0.01
  weight_decay: 0.001
dataloader:
  shuffle: True
  batch_size: 16
  num_workers: 0
  train_eval: 1000
transform:
  in_h: 128
  in_w: 128
  pad_tuple:
  - 0
  - 0
  - 0
  - 0
  static: False
