random_seed: 123
train_fraction: 1
val_fraction: 0
resume_checkpoint:
residual: 0e4025d9ded54281898b14ab4f0fa7c9
epochs: 5
parallel_backend: 
n_process: 
amp_mode:
scaler:
optimizer:
  lr: 0.01
  weight_decay: 0.0001
dataloader:
  shuffle: True
  batch_size: 1
  num_workers: 0
  train_eval: 1000
transform:
  in_h: 128
  in_w: 128
  pad_tuple:
  - 0
  - 0
  - 0
  - 0
  static: False
